# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('des', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
