# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 05:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170817_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 5, 55, 4, 665234, tzinfo=utc), verbose_name='date published'),
        ),
    ]
