# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 07:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20170817_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 7, 30, 47, 410955, tzinfo=utc), verbose_name='date published'),
        ),
    ]
